name: Main Entrypoint

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Select Operating System'
        required: true
        type: choice
        options:
        - windows-latest
        - windows-11-arm
        - macos-latest
        - ubuntu-latest
        default: 'windows-latest'
      username:
        description: 'Custom Username'
        required: true
        type: string
        default: 'Ashik'
      tunnel_provider:
        description: 'Select Tunnel Provider'
        required: true
        type: choice
        options:
        - ngrok
        - cloudflare
        default: 'ngrok'
      region:
        description: 'Select Ngrok Tunnel Region (only for ngrok)'
        required: true
        type: choice
        options:
        - "us"
        - "eu"
        - "ap"
        - "au"
        - "sa"
        - "jp"
        - "in"
        default: 'in'
      timeout:
        description: 'Session Timeout (minutes, max 360)'
        required: true
        type: string
        default: '360'
      install_virtual_sound_card:
        description: 'Install Virtual Sound Card'
        required: false
        type: boolean
        default: false
      set_default_browser:
        description: 'Set Default Browser to Chrome/BrowserOS'
        required: false
        type: string
        default: 'chrome'

jobs:
  call-windows-workflow:
    if: ${{ contains(github.event.inputs.os, 'windows') }}
    uses: ./.github/workflows/windows.yml
    with:
      os: ${{ github.event.inputs.os }}
      username: ${{ github.event.inputs.username }}
      tunnel_provider: ${{ github.event.inputs.tunnel_provider }}
      region: ${{ github.event.inputs.region }}
      timeout: ${{ github.event.inputs.timeout }}
      install_virtual_sound_card: ${{ github.event.inputs.install_virtual_sound_card }}
      set_default_browser: ${{ github.event.inputs.set_default_browser }}
    secrets:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

  call-macos-workflow:
    if: ${{ github.event.inputs.os == 'macos-latest' }}
    uses: ./.github/workflows/macos.yml
    with:
      username: ${{ github.event.inputs.username }}
      tunnel_provider: ${{ github.event.inputs.tunnel_provider }}
      region: ${{ github.event.inputs.region }}
      timeout: ${{ github.event.inputs.timeout }}
      install_virtual_sound_card: ${{ github.event.inputs.install_virtual_sound_card }}
    secrets:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      CF_TUNNEL_TOKEN: ${{ secrets.CF_TUNNEL_TOKEN }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

  call-ubuntu-workflow:
    if: ${{ github.event.inputs.os == 'ubuntu-latest' }}
    uses: ./.github/workflows/ubuntu.yml
    with:
      username: ${{ github.event.inputs.username }}
      tunnel_provider: ${{ github.event.inputs.tunnel_provider }}
      region: ${{ github.event.inputs.region }}
      timeout: ${{ github.event.inputs.timeout }}
      install_virtual_sound_card: ${{ github.event.inputs.install_virtual_sound_card }}
    secrets:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      CF_TUNNEL_TOKEN: ${{ secrets.CF_TUNNEL_TOKEN }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
