name: Main Entrypoint

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Select Operating System'
        required: true
        type: choice
        options:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        default: 'windows-latest'
      username:
        description: 'Custom Username'
        required: true
        type: string
        default: 'Ashik'
      tunnel_provider:
        description: 'Select Tunnel Provider'
        required: true
        type: choice
        options:
          - ngrok
          - cloudflare
        default: 'ngrok'
      region:
        description: 'Select Ngrok Tunnel Region (only for ngrok)'
        required: true
        type: choice
        options:
          - "us"
          - "eu"
          - "ap"
          - "au"
          - "sa"
          - "jp"
          - "in"
        default: 'in'
      timeout:
        description: 'Session Timeout (minutes, max 360)'
        required: true
        type: string
        default: '360'
      install_apps:
        description: 'Apps to install (comma-separated: virtual_sound_card)'
        required: false
        type: string
        default: ''
      set_default_browser:
        description: 'Set Default Browser to Chrome/BrowserOS'
        required: false
        type: string
        default: 'chrome'
      enable_google_drive_persistence:
        description: 'Enable Google Drive Persistence (Windows only)'
        required: false
        type: boolean
        default: true

jobs:
  call-windows-workflow:
    if: ${{ github.event.inputs.os == 'windows-latest' }}
    uses: ./.github/workflows/windows.yml
    with:
      username: ${{ github.event.inputs.username }}
      tunnel_provider: ${{ github.event.inputs.tunnel_provider }}
      region: ${{ github.event.inputs.region }}
      timeout: ${{ github.event.inputs.timeout }}
      install_virtual_sound_card: "${{ contains(github.event.inputs.install_apps, 'virtual_sound_card') }}"
      set_default_browser: ${{ github.event.inputs.set_default_browser }}
      enable_google_drive_persistence: "${{ github.event.inputs.enable_google_drive_persistence }}"
    secrets:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}

  call-macos-workflow:
    if: ${{ github.event.inputs.os == 'macos-latest' }}
    uses: ./.github/workflows/macos.yml
    with:
      username: ${{ github.event.inputs.username }}
      tunnel_provider: ${{ github.event.inputs.tunnel_provider }}
      region: ${{ github.event.inputs.region }}
      timeout: ${{ github.event.inputs.timeout }}
      install_virtual_sound_card: "${{ contains(github.event.inputs.install_apps, 'virtual_sound_card') }}"
    secrets:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      CF_TUNNEL_TOKEN: ${{ secrets.CF_TUNNEL_TOKEN }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

  call-ubuntu-workflow:
    if: ${{ github.event.inputs.os == 'ubuntu-latest' }}
    uses: ./.github/workflows/ubuntu.yml
    with:
      username: ${{ github.event.inputs.username }}
      tunnel_provider: ${{ github.event.inputs.tunnel_provider }}
      region: ${{ github.event.inputs.region }}
      timeout: ${{ github.event.inputs.timeout }}
      install_virtual_sound_card: "${{ contains(github.event.inputs.install_apps, 'virtual_sound_card') }}"
    secrets:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      CF_TUNNEL_TOKEN: ${{ secrets.CF_TUNNEL_TOKEN }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
