name: macOS

on:
  workflow_call:
    inputs:
      username:
        description: 'Custom Username'
        required: true
        type: string
      tunnel_provider:
        description: 'Select Tunnel Provider'
        required: true
        type: string
      region:
        description: 'Select Ngrok Tunnel Region'
        required: true
        type: string
      timeout:
        description: 'Session Timeout (minutes, max 360)'
        required: true
        type: string
      install_virtual_sound_card:
        description: 'Install Virtual Sound Card (BlackHole)'
        required: false
        type: boolean
        default: false
      install_github_desktop:
        description: 'Install GitHub Desktop'
        required: false
        type: boolean
        default: false
      install_vscode:
        description: 'Install VS Code'
        required: false
        type: boolean
        default: false
    secrets:
      NGROK_AUTH_TOKEN:
        required: true
      CF_TUNNEL_TOKEN:
        required: true
      USER_PASSWORD:
        required: true

jobs:
  rdp-session:
    runs-on: macos-latest
    timeout-minutes: ${{ fromJSON(inputs.timeout) }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run pre-install script
        env:
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          INSTALL_VIRTUAL_SOUND_CARD: ${{ inputs.install_virtual_sound_card }}
          INSTALL_GITHUB_DESKTOP: ${{ inputs.install_github_desktop }}
          INSTALL_VSCODE: ${{ inputs.install_vscode }}
        run: |
          chmod +x ./scripts/preinstall-mac.sh
          ./scripts/preinstall-mac.sh "${{ inputs.username }}"

      - name: Install jq
        run: |
          brew install jq
        shell: bash

      - name: Setup Ngrok Tunnel
        if: inputs.tunnel_provider == 'ngrok'
        shell: bash
        run: |
          REGION="${{ inputs.region }}"
          AUTH_TOKEN="${{ secrets.NGROK_AUTH_TOKEN }}"
          NGROK_LOG="ngrok.log"
          CONFIG_FILE="ngrok.yml"
          PORT="5900"

          echo "version: \"2\"" > $CONFIG_FILE
          echo "authtoken: $AUTH_TOKEN" >> $CONFIG_FILE
          echo "region: $REGION" >> $CONFIG_FILE

          echo "Installing ngrok..."
          brew install ngrok

          echo "Starting ngrok tunnel on port $PORT..."
          nohup ngrok tcp $PORT --config "$CONFIG_FILE" --log "$NGROK_LOG" > /dev/null 2>&1 &

          echo "Waiting for ngrok to start..."
          sleep 15

          for i in {1..5}; do
            TUNNEL_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url // empty')
            if [ -n "$TUNNEL_URL" ]; then
              break
            fi
            echo "Attempt $i: Tunnel not ready yet, waiting..."
            sleep 5
          done

          if [ -z "$TUNNEL_URL" ]; then
            echo "::error::Failed to get ngrok tunnel info after multiple attempts."
            echo "Ngrok log content:"
            cat "$NGROK_LOG" 2>/dev/null || echo "No ngrok log found"
            exit 1
          fi

          RDP_ADDRESS=$(echo "$TUNNEL_URL" | sed 's|tcp://||' | cut -d: -f1)
          RDP_PORT=$(echo "$TUNNEL_URL" | sed 's|tcp://||' | cut -d: -f2)
          echo "RDP_ADDRESS=$RDP_ADDRESS" >> $GITHUB_ENV
          echo "RDP_PORT=$RDP_PORT" >> $GITHUB_ENV
          echo "Tunnel established successfully: $TUNNEL_URL"

      - name: Setup Cloudflare Tunnel
        if: inputs.tunnel_provider == 'cloudflare'
        shell: bash
        run: |
          echo "Installing cloudflared..."
          brew install cloudflare/cloudflare/cloudflared

          echo "Starting cloudflare tunnel..."
          CF_LOG="cloudflared.log"
          TOKEN="${{ secrets.CF_TUNNEL_TOKEN }}"

          if [ -z "$TOKEN" ]; then
            echo "::error::Cloudflare tunnel token is not set. Please set the CF_TUNNEL_TOKEN secret."
            exit 1
          fi

          nohup cloudflared tunnel run --token $TOKEN > $CF_LOG 2>&1 &

          echo "Waiting for cloudflared to start..."
          sleep 15

      - name: Display Connection Details (Ngrok)
        if: inputs.tunnel_provider == 'ngrok'
        run: |
          echo "🎯 CONNECTION DETAILS 🎯"
          echo "=========================================="
          echo "OS: macos-latest"
          echo "Protocol: VNC (Use a VNC Viewer like RealVNC or TightVNC)"
          echo "Port: 5900"
          echo "Address: ${{ env.RDP_ADDRESS }}"
          echo "Port: ${{ env.RDP_PORT }}"
          echo "Username: ${{ inputs.username }}"
          echo "Password: ${{ secrets.USER_PASSWORD }}"
          echo "=========================================="
          echo "Connection string: ${{ env.RDP_ADDRESS }}:${{ env.RDP_PORT }}"
        shell: bash

      - name: Display Connection Details (Cloudflare)
        if: inputs.tunnel_provider == 'cloudflare'
        run: |
          echo "🎯 CONNECTION DETAILS 🎯"
          echo "=========================================="
          echo "OS: macos-latest"
          echo "Protocol: VNC (Use a VNC Viewer like RealVNC or TightVNC)"
          echo "Address: Please check your Cloudflare dashboard for your tunnel hostname."
          echo "Username: ${{ inputs.username }}"
          echo "Password: ${{ secrets.USER_PASSWORD }}"
          echo "=========================================="
          echo "Cloudflared log:"
          cat cloudflared.log 2>/dev/null || echo "No cloudflared log found"
        shell: bash

      - name: Keep Workflow Alive
        shell: bash
        run: |
          echo "Remote desktop session is now active!"
          echo "The workflow will remain running for ${{ inputs.timeout }} minutes."
          echo "Press Ctrl+C in the workflow logs to terminate the session early."
          sleep ${{ inputs.timeout }}m